# Generated by Django 4.1.3 on 2022-11-10 20:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0002_alter_post_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, editable=False
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="draft",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="media/post"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="modified",
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                default=django.utils.timezone.now,
                editable=False,
                max_length=150,
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
